name: Update streak stats

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - ".github/workflows/streak-stats.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@51cfb8879073b4c016ce6286016de0b14d179077 # v1.7.0
        with:
          options: user=nikagagua&theme=github-dark-blue&hide_border=true&stroke=6baaf1&ring=6565d3&fire=6565d3&currStreakNum=6baaf1&sideNums=6baaf1&currStreakLabel=8888e8&sideLabels=8888e8&dates=5a6375&background=0c1115&disable_animations=true
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "Nika Gagua"
          git config user.email "97543752+Nikagagua@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "chore: update streak stats" || exit 0
          git push
